In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
# List , Dictionary , Tuple
List=[20,30,10,40,50,60]
List[1]

In [2]:
dict={"Hello":"hi","Ezhil":"pranesh","brother":"sister"}

In [17]:
dict["brother"]
dict.values()
dict.keys()

dict_keys(['Hello', 'Ezhil', 'brother'])

In [6]:
student_dict={"student1":["VCET","VET"],
              "student2":["kongu_arts","kongu_engineering"],
              "student3":["nandha_arts","nandha_engineering"]}

In [7]:
student_dict["student1"]

['VCET', 'VET']

In [8]:
student_dict["student2"][1]

'kongu_engineering'

In [9]:
[val for k,val in student_dict.items()]

[['VCET', 'VET'],
 ['kongu_arts', 'kongu_engineering'],
 ['nandha_arts', 'nandha_engineering']]

In [11]:
x=["abc",1,'c']
dist_ex={"s1":["HCL","TCS"],"s2":["Benz"]}

In [ ]:
for k,v in dist_ex.items():
    if k=="s1":
        print(k)
        print(v)

In [ ]:
x.append("h")
x

In [ ]:
#tuple--> immutable
#list --> mutable
tup_ex=(1,2,3,1)
myList=[1,2,3,4,5,6]

In [ ]:
myList.append(tup_ex)
myList


In [ ]:
!pip install pandas

In [1]:
import pandas as pd 

In [2]:
df=pd.read_csv("My Uber Drives - 2016.csv")

In [12]:
df


START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*  
0          Fort Pierce      5.1   Meal/Entertain  
1          Fort Pierce      5.0              NaN  
2          Fort Pierce      4.8  Errand/Supplies  
3          Fort Pierce      4.7          Meeting  
4      West Palm Beach     63.7   Customer Visit  
...                ...      ...              ...  
1151  Unknown Location      3.9   Temporary Site  
1152  Unknown Location     16.2          Meeting  
1153           Gampaha      6.4   Temporary Site  
1154         Ilukwatta     48.2   Temporary Site  
1155               NaN  12204.7              NaN  

[1156 rows x 7 columns]

In [6]:
type(df)

pandas.core.frame.DataFrame

In [100]:
df.dtypes

START_DATE*     object
END_DATE*       object
CATEGORY*       object
START*          object
STOP*           object
MILES*         float64
PURPOSE*        object
dtype: object

In [5]:
df.head()
#shift +tab
#print first five line

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  
0     5.1   Meal/Entertain  
1     5.0              NaN  
2     4.8  Errand/Supplies  
3     4.7          Meeting  
4    63.7   Customer Visit

In [6]:
df.head(n=10)

START_DATE*        END_DATE* CATEGORY*           START*  \
0   1/1/2016 21:11   1/1/2016 21:17  Business      Fort Pierce   
1    1/2/2016 1:25    1/2/2016 1:37  Business      Fort Pierce   
2   1/2/2016 20:25   1/2/2016 20:38  Business      Fort Pierce   
3   1/5/2016 17:31   1/5/2016 17:45  Business      Fort Pierce   
4   1/6/2016 14:42   1/6/2016 15:49  Business      Fort Pierce   
5   1/6/2016 17:15   1/6/2016 17:19  Business  West Palm Beach   
6   1/6/2016 17:30   1/6/2016 17:35  Business  West Palm Beach   
7   1/7/2016 13:27   1/7/2016 13:33  Business             Cary   
8   1/10/2016 8:05   1/10/2016 8:25  Business             Cary   
9  1/10/2016 12:17  1/10/2016 12:44  Business          Jamaica   

             STOP*  MILES*         PURPOSE*  
0      Fort Pierce     5.1   Meal/Entertain  
1      Fort Pierce     5.0              NaN  
2      Fort Pierce     4.8  Errand/Supplies  
3      Fort Pierce     4.7          Meeting  
4  West Palm Beach    63.7   Customer Visit  
5  West Palm Beach     4.3   Meal/Entertain  
6       Palm Beach     7.1          Meeting  
7             Cary     0.8          Meeting  
8      Morrisville     8.3          Meeting  
9         New York    16.5   Customer Visit

In [8]:
df.shape

(1156, 7)

In [9]:
df.tail()

START_DATE*         END_DATE* CATEGORY*            START*  \
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
1151  Unknown Location      3.9  Temporary Site  
1152  Unknown Location     16.2         Meeting  
1153           Gampaha      6.4  Temporary Site  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN

In [32]:
temp=pd.DataFrame({"A":["1","2","3"],"B":[11,12,13],"C":["12-06-2012","13-06-2015","15-06-2017"]})

In [18]:
temp

A   B           C
0  1  11  12-06-2012
1  2  12  13-06-2015
2  3  13  15-06-2017

In [17]:
temp.dtypes

A    object
B     int64
C    object
dtype: object

In [21]:
pd.to_datetime("2002-11-02")

Timestamp('2002-11-02 00:00:00')

In [34]:
pd.to_datetime(["2002-11-02","2002-11-02","2006-1-07"])

DatetimeIndex(['2002-11-02', '2002-11-02', '2006-01-07'], dtype='datetime64[ns]', freq=None)

In [33]:
temp.dtypes

A    object
B     int64
C    object
dtype: object

In [37]:
temp["C"]=pd.to_datetime(temp["C"])

In [57]:
temp.dtypes

A             int64
B             int64
C    datetime64[ns]
dtype: object

In [49]:
pd.to_datetime(["2002-sep-11","abc"],errors="coerce") 

DatetimeIndex(['2002-09-11', 'NaT'], dtype='datetime64[ns]', freq=None)

In [56]:
temp["A"]=pd.to_numeric(temp["A"])

In [59]:
temp["A"]=temp["A"].astype(str)

In [60]:
df.head()

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  
0     5.1   Meal/Entertain  
1     5.0              NaN  
2     4.8  Errand/Supplies  
3     4.7          Meeting  
4    63.7   Customer Visit

In [70]:
import datetime

In [85]:
df["START_DATE*"]=pd.to_datetime(df["START_DATE*"],format='%m/%d/%Y %H:%M',errors='coerce')

In [86]:
df.dtypes

START_DATE*    datetime64[ns]
END_DATE*              object
CATEGORY*              object
START*                 object
STOP*                  object
MILES*                float64
PURPOSE*               object
dtype: object

In [87]:
df.describe()
#show up only int type

MILES*
count   1156.000000
mean      21.115398
std      359.299007
min        0.500000
25%        2.900000
50%        6.000000
75%       10.400000
max    12204.700000

In [88]:
df.describe(include="all")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8780\1985922364.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include="all")


START_DATE*        END_DATE* CATEGORY* START* STOP*  \
count                  1155             1155      1155   1155  1155   
unique                 1154             1154         2    177   188   
top     2016-06-28 23:34:00  6/28/2016 23:59  Business   Cary  Cary   
freq                      2                2      1078    201   203   
first   2016-01-01 21:11:00              NaN       NaN    NaN   NaN   
last    2016-12-31 22:08:00              NaN       NaN    NaN   NaN   
mean                    NaN              NaN       NaN    NaN   NaN   
std                     NaN              NaN       NaN    NaN   NaN   
min                     NaN              NaN       NaN    NaN   NaN   
25%                     NaN              NaN       NaN    NaN   NaN   
50%                     NaN              NaN       NaN    NaN   NaN   
75%                     NaN              NaN       NaN    NaN   NaN   
max                     NaN              NaN       NaN    NaN   NaN   

              MILES* PURPOSE*  
count    1156.000000      653  
unique           NaN       10  
top              NaN  Meeting  
freq             NaN      187  
first            NaN      NaN  
last             NaN      NaN  
mean       21.115398      NaN  
std       359.299007      NaN  
min         0.500000      NaN  
25%         2.900000      NaN  
50%         6.000000      NaN  
75%        10.400000      NaN  
max     12204.700000      NaN

In [92]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0    2016-01-01 21:11:00    1/1/2016 21:17  Business       Fort Pierce   
1    2016-01-02 01:25:00     1/2/2016 1:37  Business       Fort Pierce   
2    2016-01-02 20:25:00    1/2/2016 20:38  Business       Fort Pierce   
3    2016-01-05 17:31:00    1/5/2016 17:45  Business       Fort Pierce   
4    2016-01-06 14:42:00    1/6/2016 15:49  Business       Fort Pierce   
...                  ...               ...       ...               ...   
1151 2016-12-31 13:24:00  12/31/2016 13:42  Business           Kar?chi   
1152 2016-12-31 15:03:00  12/31/2016 15:38  Business  Unknown Location   
1153 2016-12-31 21:32:00  12/31/2016 21:50  Business        Katunayake   
1154 2016-12-31 22:08:00  12/31/2016 23:51  Business           Gampaha   
1155                 NaT               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*  
0          Fort Pierce      5.1   Meal/Entertain  
1          Fort Pierce      5.0              NaN  
2          Fort Pierce      4.8  Errand/Supplies  
3          Fort Pierce      4.7          Meeting  
4      West Palm Beach     63.7   Customer Visit  
...                ...      ...              ...  
1151  Unknown Location      3.9   Temporary Site  
1152  Unknown Location     16.2          Meeting  
1153           Gampaha      6.4   Temporary Site  
1154         Ilukwatta     48.2   Temporary Site  
1155               NaN  12204.7              NaN  

[1156 rows x 7 columns]

In [96]:
df["START*"].value_counts()
#Count the count of unique value
df["START*"].value_counts().head()
#by adding head it shows the top five count of unique value

Cary                201
Unknown Location    148
Morrisville          85
Whitebridge          68
Islamabad            57
Name: START*, dtype: int64

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   START_DATE*  1155 non-null   datetime64[ns]
 1   END_DATE*    1155 non-null   object        
 2   CATEGORY*    1155 non-null   object        
 3   START*       1155 non-null   object        
 4   STOP*        1155 non-null   object        
 5   MILES*       1156 non-null   float64       
 6   PURPOSE*     653 non-null    object        
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 63.3+ KB


# 5 verbs of data Manipulation

### 1.Selecting / Indexing
### 2.Filtering
### 3.Sorting
### 4.Mutating /  Conditionality adding columns
### 5.Group by / Summarize

#  1 .Selecting / indexing

In [102]:
df.head()

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  
0     5.1   Meal/Entertain  
1     5.0              NaN  
2     4.8  Errand/Supplies  
3     4.7          Meeting  
4    63.7   Customer Visit

In [104]:
df.iloc[0:5,0:4] #df.iloc[row,column]

START_DATE*       END_DATE* CATEGORY*       START*
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce

In [107]:
df.iloc[0:5,[2,4]] # selecting second and fourth column

CATEGORY*            STOP*
0  Business      Fort Pierce
1  Business      Fort Pierce
2  Business      Fort Pierce
3  Business      Fort Pierce
4  Business  West Palm Beach

In [108]:
df.iloc[0:5]  #  5 row and all column

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  
0     5.1   Meal/Entertain  
1     5.0              NaN  
2     4.8  Errand/Supplies  
3     4.7          Meeting  
4    63.7   Customer Visit

In [110]:
df.iloc[:,0:3] # All row and 3 column

START_DATE*         END_DATE* CATEGORY*
0       1/1/2016 21:11    1/1/2016 21:17  Business
1        1/2/2016 1:25     1/2/2016 1:37  Business
2       1/2/2016 20:25    1/2/2016 20:38  Business
3       1/5/2016 17:31    1/5/2016 17:45  Business
4       1/6/2016 14:42    1/6/2016 15:49  Business
...                ...               ...       ...
1151  12/31/2016 13:24  12/31/2016 13:42  Business
1152  12/31/2016 15:03  12/31/2016 15:38  Business
1153  12/31/2016 21:32  12/31/2016 21:50  Business
1154  12/31/2016 22:08  12/31/2016 23:51  Business
1155            Totals               NaN       NaN

[1156 rows x 3 columns]

In [9]:
df.iloc[:,: -1]

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*  
0          Fort Pierce      5.1  
1          Fort Pierce      5.0  
2          Fort Pierce      4.8  
3          Fort Pierce      4.7  
4      West Palm Beach     63.7  
...                ...      ...  
1151  Unknown Location      3.9  
1152  Unknown Location     16.2  
1153           Gampaha      6.4  
1154         Ilukwatta     48.2  
1155               NaN  12204.7  

[1156 rows x 6 columns]

In [14]:
#Lable Based Indexing
df.loc[:,["START*","STOP*"]]# if you remove ":"it show error

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [19]:
df[["START*","STOP*"]]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [36]:
ab=df.loc[:,"START*"] # printed in series not as table type:series
ab=df.loc[:,["START*"]]# print as atable formate   type:dataframe

In [35]:
type(ab) 

pandas.core.frame.DataFrame

In [32]:
ab


START*
0          Fort Pierce
1          Fort Pierce
2          Fort Pierce
3          Fort Pierce
4          Fort Pierce
...                ...
1151           Kar?chi
1152  Unknown Location
1153        Katunayake
1154           Gampaha
1155               NaN

[1156 rows x 1 columns]

In [34]:
df.loc[:,"START*","STOP*"] #so erroe, series is a single column

IndexingError: Too many indexers

In [48]:
df.loc[0:4,["START_DATE*","MILES*"]]# difference between ilow and low

START_DATE*  MILES*
0  1/1/2016 21:11     5.1
1   1/2/2016 1:25     5.0
2  1/2/2016 20:25     4.8
3  1/5/2016 17:31     4.7
4  1/6/2016 14:42    63.7

In [52]:
df.iloc[0:5,[0,5]]# in dexexing we use [0.4] and [0:5] another 0,5 and start,miles

START_DATE*  MILES*
0  1/1/2016 21:11     5.1
1   1/2/2016 1:25     5.0
2  1/2/2016 20:25     4.8
3  1/5/2016 17:31     4.7
4  1/6/2016 14:42    63.7

In [51]:
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

# Filtering

In [55]:
df["MILES*"] > 10 

0       False
1       False
2       False
3       False
4        True
        ...  
1151    False
1152     True
1153    False
1154     True
1155     True
Name: MILES*, Length: 1156, dtype: bool

In [67]:
df2=df.loc[df["MILES*"]>10,["START_DATE*","MILES*"]]
df2

START_DATE*   MILES*
4       1/6/2016 14:42     63.7
9      1/10/2016 12:17     16.5
10     1/10/2016 15:08     10.8
22     1/12/2016 16:02     15.1
23     1/13/2016 13:54     11.2
...                ...      ...
1134  12/29/2016 11:28     11.9
1144  12/29/2016 23:14     12.9
1152  12/31/2016 15:03     16.2
1154  12/31/2016 22:08     48.2
1155            Totals  12204.7

[316 rows x 2 columns]

In [64]:
df[df["MILES*"]>10]

START_DATE*         END_DATE* CATEGORY*            START*  \
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
9      1/10/2016 12:17   1/10/2016 12:44  Business           Jamaica   
10     1/10/2016 15:08   1/10/2016 15:51  Business          New York   
22     1/12/2016 16:02   1/12/2016 17:00  Business          New York   
23     1/13/2016 13:54   1/13/2016 14:07  Business          Downtown   
...                ...               ...       ...               ...   
1134  12/29/2016 11:28  12/29/2016 12:00  Business  Unknown Location   
1144  12/29/2016 23:14  12/29/2016 23:47  Business  Unknown Location   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
4      West Palm Beach     63.7  Customer Visit  
9             New York     16.5  Customer Visit  
10              Queens     10.8         Meeting  
22       Queens County     15.1         Meeting  
23             Gulfton     11.2         Meeting  
...                ...      ...             ...  
1134           Kar?chi     11.9  Meal/Entertain  
1144           Kar?chi     12.9         Meeting  
1152  Unknown Location     16.2         Meeting  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN  

[316 rows x 7 columns]

In [74]:
# Find out all the rides from city cary
df.loc[df["START*"]=="Cary",["MILES*"]].head()

MILES*
7      0.8
8      8.3
28    10.4
30     4.8
34    17.1

In [78]:
# FInd the ride start from new york 
df.loc[df["START*"]=="New York"]

START_DATE*        END_DATE* CATEGORY*    START*             STOP*  \
10   1/10/2016 15:08  1/10/2016 15:51  Business  New York            Queens   
22   1/12/2016 16:02  1/12/2016 17:00  Business  New York     Queens County   
106  2/14/2016 16:35  2/14/2016 17:02  Business  New York  Long Island City   
423  6/10/2016 15:19  6/10/2016 16:28  Business  New York           Jamaica   

     MILES* PURPOSE*  
10     10.8  Meeting  
22     15.1  Meeting  
106    13.0  Meeting  
423    16.3  Meeting

In [82]:
df.loc[df["START*"].isin(["Cary","New York"])].shape

(205, 7)

In [120]:
df2=df.loc[df["START*"].isin(["Cary","New York"])]
df2.head(2)

START_DATE*       END_DATE* CATEGORY* START*        STOP*  MILES*  \
7  1/7/2016 13:27  1/7/2016 13:33  Business   Cary         Cary     0.8   
8  1/10/2016 8:05  1/10/2016 8:25  Business   Cary  Morrisville     8.3   

  PURPOSE*  
7  Meeting  
8  Meeting

In [121]:
 df2.loc[0:5,:] # difference between iloc and loc

Empty DataFrame
Columns: [START_DATE*, END_DATE*, CATEGORY*, START*, STOP*, MILES*, PURPOSE*]
Index: []

In [122]:
df2.iloc[0:5,:]

START_DATE*        END_DATE* CATEGORY*    START*          STOP*  \
7    1/7/2016 13:27   1/7/2016 13:33  Business      Cary           Cary   
8    1/10/2016 8:05   1/10/2016 8:25  Business      Cary    Morrisville   
10  1/10/2016 15:08  1/10/2016 15:51  Business  New York         Queens   
22  1/12/2016 16:02  1/12/2016 17:00  Business  New York  Queens County   
28  1/15/2016 11:43  1/15/2016 12:03  Business      Cary         Durham   

    MILES*        PURPOSE*  
7      0.8         Meeting  
8      8.3         Meeting  
10    10.8         Meeting  
22    15.1         Meeting  
28    10.4  Meal/Entertain

In [123]:
# Find all trips with distance > 10 miles and originating from cary and morris
df.loc[(df["START*"].isin(["Cary","Morrisville"]))&(df["MILES*"]>10)]
df.loc[(df["START*"].isin(["Cary","Morrisville"]))|(df["MILES*"]>10)]

START_DATE*         END_DATE* CATEGORY*            START*  \
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
7       1/7/2016 13:27    1/7/2016 13:33  Business              Cary   
8       1/10/2016 8:05    1/10/2016 8:25  Business              Cary   
9      1/10/2016 12:17   1/10/2016 12:44  Business           Jamaica   
10     1/10/2016 15:08   1/10/2016 15:51  Business          New York   
...                ...               ...       ...               ...   
1134  12/29/2016 11:28  12/29/2016 12:00  Business  Unknown Location   
1144  12/29/2016 23:14  12/29/2016 23:47  Business  Unknown Location   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
4      West Palm Beach     63.7  Customer Visit  
7                 Cary      0.8         Meeting  
8          Morrisville      8.3         Meeting  
9             New York     16.5  Customer Visit  
10              Queens     10.8         Meeting  
...                ...      ...             ...  
1134           Kar?chi     11.9  Meal/Entertain  
1144           Kar?chi     12.9         Meeting  
1152  Unknown Location     16.2         Meeting  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN  

[536 rows x 7 columns]

In [124]:
df2.reset_index() #not change in the orignal data that is df2


index       START_DATE*         END_DATE* CATEGORY*    START*  \
0        7    1/7/2016 13:27    1/7/2016 13:33  Business      Cary   
1        8    1/10/2016 8:05    1/10/2016 8:25  Business      Cary   
2       10   1/10/2016 15:08   1/10/2016 15:51  Business  New York   
3       22   1/12/2016 16:02   1/12/2016 17:00  Business  New York   
4       28   1/15/2016 11:43   1/15/2016 12:03  Business      Cary   
..     ...               ...               ...       ...       ...   
200   1049  12/13/2016 20:20  12/13/2016 20:29  Business      Cary   
201   1050  12/14/2016 16:52  12/14/2016 17:10  Business      Cary   
202   1051  12/14/2016 17:22  12/14/2016 17:34  Business      Cary   
203   1052  12/14/2016 17:50  12/14/2016 18:00  Business      Cary   
204   1054  12/15/2016 14:20  12/15/2016 14:54  Business      Cary   

             STOP*  MILES*        PURPOSE*  
0             Cary     0.8         Meeting  
1      Morrisville     8.3         Meeting  
2           Queens    10.8         Meeting  
3    Queens County    15.1         Meeting  
4           Durham    10.4  Meal/Entertain  
..             ...     ...             ...  
200           Cary     4.1  Meal/Entertain  
201           Cary     3.4             NaN  
202           Cary     3.3             NaN  
203    Morrisville     3.0  Meal/Entertain  
204    Morrisville    10.6         Meeting  

[205 rows x 8 columns]

In [125]:
df2

START_DATE*         END_DATE* CATEGORY*    START*          STOP*  \
7       1/7/2016 13:27    1/7/2016 13:33  Business      Cary           Cary   
8       1/10/2016 8:05    1/10/2016 8:25  Business      Cary    Morrisville   
10     1/10/2016 15:08   1/10/2016 15:51  Business  New York         Queens   
22     1/12/2016 16:02   1/12/2016 17:00  Business  New York  Queens County   
28     1/15/2016 11:43   1/15/2016 12:03  Business      Cary         Durham   
...                ...               ...       ...       ...            ...   
1049  12/13/2016 20:20  12/13/2016 20:29  Business      Cary           Cary   
1050  12/14/2016 16:52  12/14/2016 17:10  Business      Cary           Cary   
1051  12/14/2016 17:22  12/14/2016 17:34  Business      Cary           Cary   
1052  12/14/2016 17:50  12/14/2016 18:00  Business      Cary    Morrisville   
1054  12/15/2016 14:20  12/15/2016 14:54  Business      Cary    Morrisville   

      MILES*        PURPOSE*  
7        0.8         Meeting  
8        8.3         Meeting  
10      10.8         Meeting  
22      15.1         Meeting  
28      10.4  Meal/Entertain  
...      ...             ...  
1049     4.1  Meal/Entertain  
1050     3.4             NaN  
1051     3.3             NaN  
1052     3.0  Meal/Entertain  
1054    10.6         Meeting  

[205 rows x 7 columns]

In [130]:
df2.reset_index(inplace=True,drop=True)

In [131]:
df2

START_DATE*         END_DATE* CATEGORY*    START*          STOP*  \
0      1/7/2016 13:27    1/7/2016 13:33  Business      Cary           Cary   
1      1/10/2016 8:05    1/10/2016 8:25  Business      Cary    Morrisville   
2     1/10/2016 15:08   1/10/2016 15:51  Business  New York         Queens   
3     1/12/2016 16:02   1/12/2016 17:00  Business  New York  Queens County   
4     1/15/2016 11:43   1/15/2016 12:03  Business      Cary         Durham   
..                ...               ...       ...       ...            ...   
200  12/13/2016 20:20  12/13/2016 20:29  Business      Cary           Cary   
201  12/14/2016 16:52  12/14/2016 17:10  Business      Cary           Cary   
202  12/14/2016 17:22  12/14/2016 17:34  Business      Cary           Cary   
203  12/14/2016 17:50  12/14/2016 18:00  Business      Cary    Morrisville   
204  12/15/2016 14:20  12/15/2016 14:54  Business      Cary    Morrisville   

     MILES*        PURPOSE*  
0       0.8         Meeting  
1       8.3         Meeting  
2      10.8         Meeting  
3      15.1         Meeting  
4      10.4  Meal/Entertain  
..      ...             ...  
200     4.1  Meal/Entertain  
201     3.4             NaN  
202     3.3             NaN  
203     3.0  Meal/Entertain  
204    10.6         Meeting  

[205 rows x 7 columns]

# Sorting

In [138]:
df.sort_values(by=["MILES*"],ascending=False)

START_DATE*         END_DATE* CATEGORY*            START*  \
1155            Totals               NaN       NaN               NaN   
269    3/25/2016 16:52   3/25/2016 22:22  Business             Latta   
270    3/25/2016 22:54    3/26/2016 1:39  Business      Jacksonville   
881   10/30/2016 15:22  10/30/2016 18:23  Business         Asheville   
776    9/27/2016 21:01    9/28/2016 2:37  Business  Unknown Location   
...                ...               ...       ...               ...   
1121  12/27/2016 12:53  12/27/2016 12:57  Business           Kar?chi   
1110  12/24/2016 22:04  12/24/2016 22:09  Business            Lahore   
44     1/26/2016 17:27   1/26/2016 17:29  Business              Cary   
420     6/8/2016 17:16    6/8/2016 17:18  Business              Soho   
120    2/17/2016 16:38   2/17/2016 16:43  Business        Katunayaka   

                 STOP*   MILES*         PURPOSE*  
1155               NaN  12204.7              NaN  
269       Jacksonville    310.3   Customer Visit  
270          Kissimmee    201.0          Meeting  
881             Mebane    195.9              NaN  
776   Unknown Location    195.6              NaN  
...                ...      ...              ...  
1121           Kar?chi      0.6   Meal/Entertain  
1110            Lahore      0.6  Errand/Supplies  
44                Cary      0.5  Errand/Supplies  
420            Tribeca      0.5  Errand/Supplies  
120         Katunayaka      0.5  Errand/Supplies  

[1156 rows x 7 columns]

In [141]:
df.sort_values(by=["START*","MILES*"],ascending=[True,False])
# eg: its take A and order Miles as desending then b miles as des then c....

START_DATE*         END_DATE* CATEGORY*         START*  \
906    11/4/2016 21:04   11/4/2016 21:20  Business          Agnew   
911    11/6/2016 10:50   11/6/2016 11:04  Business          Agnew   
908     11/5/2016 8:34    11/5/2016 8:43  Business          Agnew   
910    11/5/2016 19:20   11/5/2016 19:28  Business          Agnew   
879   10/30/2016 12:58  10/30/2016 13:18  Business         Almond   
...                ...               ...       ...            ...   
889    11/1/2016 17:35   11/1/2016 17:42  Business    Whitebridge   
890    11/1/2016 19:14   11/1/2016 19:20  Business    Whitebridge   
516     7/5/2016 16:48    7/5/2016 16:52  Business    Whitebridge   
870   10/28/2016 18:13  10/28/2016 20:07  Business  Winston Salem   
1155            Totals               NaN       NaN            NaN   

            STOP*   MILES*         PURPOSE*  
906          Cory      4.3              NaN  
911   Renaissance      2.4              NaN  
908   Renaissance      2.2              NaN  
910         Agnew      2.2              NaN  
879   Bryson City     15.2              NaN  
...           ...      ...              ...  
889   Whitebridge      1.2              NaN  
890   Whitebridge      1.0              NaN  
516   Whitebridge      0.6  Errand/Supplies  
870     Asheville    133.6          Meeting  
1155          NaN  12204.7              NaN  

[1156 rows x 7 columns]

# Conditional Adding Columns

In [142]:
import numpy as np

In [143]:
df["miles_cat"]=np.where(df["MILES*"]>5,"Long Trip","Short Trip")

In [144]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   miles_cat  
0          Fort Pierce      5.1   Meal/Entertain   Long Trip  
1          Fort Pierce      5.0              NaN  Short Trip  
2          Fort Pierce      4.8  Errand/Supplies  Short Trip  
3          Fort Pierce      4.7          Meeting  Short Trip  
4      West Palm Beach     63.7   Customer Visit   Long Trip  
...                ...      ...              ...         ...  
1151  Unknown Location      3.9   Temporary Site  Short Trip  
1152  Unknown Location     16.2          Meeting   Long Trip  
1153           Gampaha      6.4   Temporary Site   Long Trip  
1154         Ilukwatta     48.2   Temporary Site   Long Trip  
1155               NaN  12204.7              NaN   Long Trip  

[1156 rows x 8 columns]

In [145]:
df["my_year"]=np.array(2000)

In [146]:
df


START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   miles_cat  my_year  
0          Fort Pierce      5.1   Meal/Entertain   Long Trip     2000  
1          Fort Pierce      5.0              NaN  Short Trip     2000  
2          Fort Pierce      4.8  Errand/Supplies  Short Trip     2000  
3          Fort Pierce      4.7          Meeting  Short Trip     2000  
4      West Palm Beach     63.7   Customer Visit   Long Trip     2000  
...                ...      ...              ...         ...      ...  
1151  Unknown Location      3.9   Temporary Site  Short Trip     2000  
1152  Unknown Location     16.2          Meeting   Long Trip     2000  
1153           Gampaha      6.4   Temporary Site   Long Trip     2000  
1154         Ilukwatta     48.2   Temporary Site   Long Trip     2000  
1155               NaN  12204.7              NaN   Long Trip     2000  

[1156 rows x 9 columns]

In [148]:
df["miles_cat"].value_counts()

Long Trip     654
Short Trip    502
Name: miles_cat, dtype: int64

In [60]:
df.loc[df["MILES*"]>5].shape

(654, 7)

In [61]:
df["Miles_separation"]=np.where(df["MILES*"]<5,"Shot Trip",(np.where(df["MILES*"]>10,"Long trip","Medium")))

NameError: name 'np' is not defined

In [159]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   miles_cat  my_year  \
0          Fort Pierce      5.1   Meal/Entertain   Long Trip     2000   
1          Fort Pierce      5.0              NaN  Short Trip     2000   
2          Fort Pierce      4.8  Errand/Supplies  Short Trip     2000   
3          Fort Pierce      4.7          Meeting  Short Trip     2000   
4      West Palm Beach     63.7   Customer Visit   Long Trip     2000   
...                ...      ...              ...         ...      ...   
1151  Unknown Location      3.9   Temporary Site  Short Trip     2000   
1152  Unknown Location     16.2          Meeting   Long Trip     2000   
1153           Gampaha      6.4   Temporary Site   Long Trip     2000   
1154         Ilukwatta     48.2   Temporary Site   Long Trip     2000   
1155               NaN  12204.7              NaN   Long Trip     2000   

     Miles_separation  
0              Medium  
1              Medium  
2           Shot Trip  
3           Shot Trip  
4           Long trip  
...               ...  
1151        Shot Trip  
1152        Long trip  
1153           Medium  
1154        Long trip  
1155        Long trip  

[1156 rows x 10 columns]

# Groupby Summaries

In [17]:
df.groupby("START*")["MILES*"].agg ("mean")     #aggregate function
df.groupby("START*")["MILES*"].mean()   # same as above
# if agnew has different value of miles in dataset it takes up and mean the value

START*
Agnew                2.775000
Almond              15.200000
Apex                 5.341176
Arabi               17.000000
Arlington            4.900000
                      ...    
West University      2.200000
Weston               4.000000
Westpark Place       2.182353
Whitebridge          4.020588
Winston Salem      133.600000
Name: MILES*, Length: 177, dtype: float64

In [10]:
df.groupby("START*").mean()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9348\564090668.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("START*").mean()


MILES*
START*                     
Agnew              2.775000
Almond            15.200000
Apex               5.341176
Arabi             17.000000
Arlington          4.900000
...                     ...
West University    2.200000
Weston             4.000000
Westpark Place     2.182353
Whitebridge        4.020588
Winston Salem    133.600000

[177 rows x 1 columns]

In [15]:
 df.groupby(["START*","STOP*"]).agg(["mean","sum"]).head(20)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9348\2862730235.py:1: FutureWarning: ['START_DATE*', 'END_DATE*', 'CATEGORY*', 'PURPOSE*'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby(["START*","STOP*"]).agg(["mean","sum"]).head(20)


MILES*       
                                                           mean    sum
START*                    STOP*                                       
Agnew                     Agnew                        2.200000    2.2
                          Cory                         4.300000    4.3
                          Renaissance                  2.300000    4.6
Almond                    Bryson City                 15.200000   15.2
Apex                      Apex                         2.150000    4.3
                          Cary                         5.792308   75.3
                          Eagle Rock                   2.200000    2.2
                          Holly Springs                9.000000    9.0
Arabi                     Metairie                    17.000000   17.0
Arlington                 Washington                   4.900000    4.9
Arlington Park at Amberly Lexington Park at Amberly    1.300000    1.3
Asheville                 Mebane                     195.900000  195.9
                          Topton                      91.800000   91.8
Austin                    Katy                       136.000000  136.0
Banner Elk                Banner Elk                   6.680000   33.4
                          Boone                       15.100000   15.1
                          Elk Park                    22.400000   22.4
                          Newland                     28.100000   28.1
Bellevue                  Seattle                     12.900000   12.9
Berkeley                  El Cerrito                   2.300000    2.3

In [22]:
df5=df.groupby(["START*","STOP*"]).agg(["sum","max","min","mean"])
df5

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9348\1157163755.py:1: FutureWarning: ['START_DATE*', 'END_DATE*', 'CATEGORY*', 'PURPOSE*'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df5=df.groupby(["START*","STOP*"]).agg(["sum","max","min","mean"])


MILES*                          
                                    sum    max    min        mean
START*        STOP*                                              
Agnew         Agnew                 2.2    2.2    2.2    2.200000
              Cory                  4.3    4.3    4.3    4.300000
              Renaissance           4.6    2.4    2.2    2.300000
Almond        Bryson City          15.2   15.2   15.2   15.200000
Apex          Apex                  4.3    3.3    1.0    2.150000
...                                 ...    ...    ...         ...
Whitebridge   Wayne Ridge          31.9    8.2    7.8    7.975000
              Westpark Place       31.4    6.3    1.4    2.242857
              Whitebridge          14.1    4.2    0.6    2.014286
              Williamsburg Manor    8.3    8.3    8.3    8.300000
Winston Salem Asheville           133.6  133.6  133.6  133.600000

[363 rows x 4 columns]

In [23]:
df5.columns

MultiIndex([('MILES*',  'sum'),
            ('MILES*',  'max'),
            ('MILES*',  'min'),
            ('MILES*', 'mean')],
           )

In [32]:
 df# Find most recent & the earliest travelled date and mean distance traveled for each start city

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*  
0          Fort Pierce      5.1   Meal/Entertain  
1          Fort Pierce      5.0              NaN  
2          Fort Pierce      4.8  Errand/Supplies  
3          Fort Pierce      4.7          Meeting  
4      West Palm Beach     63.7   Customer Visit  
...                ...      ...              ...  
1151  Unknown Location      3.9   Temporary Site  
1152  Unknown Location     16.2          Meeting  
1153           Gampaha      6.4   Temporary Site  
1154         Ilukwatta     48.2   Temporary Site  
1155               NaN  12204.7              NaN  

[1156 rows x 7 columns]

In [70]:
df["START_DATE*"]=pd.to_datetime(df["START_DATE*"], format="%m/%d/%Y %H:%M",errors="coerce")

In [71]:
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0    2016-01-01 21:11:00    1/1/2016 21:17  Business       Fort Pierce   
1    2016-01-02 01:25:00     1/2/2016 1:37  Business       Fort Pierce   
2    2016-01-02 20:25:00    1/2/2016 20:38  Business       Fort Pierce   
3    2016-01-05 17:31:00    1/5/2016 17:45  Business       Fort Pierce   
4    2016-01-06 14:42:00    1/6/2016 15:49  Business       Fort Pierce   
...                  ...               ...       ...               ...   
1151 2016-12-31 13:24:00  12/31/2016 13:42  Business           Kar?chi   
1152 2016-12-31 15:03:00  12/31/2016 15:38  Business  Unknown Location   
1153 2016-12-31 21:32:00  12/31/2016 21:50  Business        Katunayake   
1154 2016-12-31 22:08:00  12/31/2016 23:51  Business           Gampaha   
1155                 NaT               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*  
0          Fort Pierce      5.1   Meal/Entertain  
1          Fort Pierce      5.0              NaN  
2          Fort Pierce      4.8  Errand/Supplies  
3          Fort Pierce      4.7          Meeting  
4      West Palm Beach     63.7   Customer Visit  
...                ...      ...              ...  
1151  Unknown Location      3.9   Temporary Site  
1152  Unknown Location     16.2          Meeting  
1153           Gampaha      6.4   Temporary Site  
1154         Ilukwatta     48.2   Temporary Site  
1155               NaN  12204.7              NaN  

[1156 rows x 7 columns]

In [73]:
df.dtypes

START_DATE*    datetime64[ns]
END_DATE*              object
CATEGORY*              object
START*                 object
STOP*                  object
MILES*                float64
PURPOSE*               object
dtype: object

In [82]:
#df.groupby("START_DATE*").agg(["min","max"]).groupby(["START_DATE*","MILES*"]).agg("mean")
#Above shows error
res=df.groupby("START*").agg({"MILES*":["mean"],"START_DATE*":["min","max"]})

In [84]:
res.reset_index(inplace=True)

In [85]:
res

START*      MILES*         START_DATE*                    
                            mean                 min                 max
0              Agnew    2.775000 2016-11-04 21:04:00 2016-11-06 10:50:00
1             Almond   15.200000 2016-10-30 12:58:00 2016-10-30 12:58:00
2               Apex    5.341176 2016-01-29 21:21:00 2016-12-12 14:26:00
3              Arabi   17.000000 2016-06-25 10:50:00 2016-06-25 10:50:00
4          Arlington    4.900000 2016-08-02 11:51:00 2016-08-02 11:51:00
..               ...         ...                 ...                 ...
172  West University    2.200000 2016-03-10 14:39:00 2016-03-16 18:43:00
173           Weston    4.000000 2016-03-05 12:57:00 2016-06-05 15:57:00
174   Westpark Place    2.182353 2016-02-26 11:05:00 2016-11-03 14:13:00
175      Whitebridge    4.020588 2016-01-19 09:09:00 2016-11-03 13:42:00
176    Winston Salem  133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00

[177 rows x 4 columns]

In [86]:
res.columns=["START_CITY","AVG_DIST","EARLIEST_TRAVEL","RECENT_TRAVEL"]

In [87]:
res

START_CITY    AVG_DIST     EARLIEST_TRAVEL       RECENT_TRAVEL
0              Agnew    2.775000 2016-11-04 21:04:00 2016-11-06 10:50:00
1             Almond   15.200000 2016-10-30 12:58:00 2016-10-30 12:58:00
2               Apex    5.341176 2016-01-29 21:21:00 2016-12-12 14:26:00
3              Arabi   17.000000 2016-06-25 10:50:00 2016-06-25 10:50:00
4          Arlington    4.900000 2016-08-02 11:51:00 2016-08-02 11:51:00
..               ...         ...                 ...                 ...
172  West University    2.200000 2016-03-10 14:39:00 2016-03-16 18:43:00
173           Weston    4.000000 2016-03-05 12:57:00 2016-06-05 15:57:00
174   Westpark Place    2.182353 2016-02-26 11:05:00 2016-11-03 14:13:00
175      Whitebridge    4.020588 2016-01-19 09:09:00 2016-11-03 13:42:00
176    Winston Salem  133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00

[177 rows x 4 columns]

In [92]:
res.groupby(["START_CITY","AVG_DIST","EARLIEST_TRAVEL"]).agg(["mean","max","min"])

RECENT_TRAVEL  \
                                                              mean   
START_CITY      AVG_DIST   EARLIEST_TRAVEL                           
Agnew           2.775000   2016-11-04 21:04:00 2016-11-06 10:50:00   
Almond          15.200000  2016-10-30 12:58:00 2016-10-30 12:58:00   
Apex            5.341176   2016-01-29 21:21:00 2016-12-12 14:26:00   
Arabi           17.000000  2016-06-25 10:50:00 2016-06-25 10:50:00   
Arlington       4.900000   2016-08-02 11:51:00 2016-08-02 11:51:00   
...                                                            ...   
West University 2.200000   2016-03-10 14:39:00 2016-03-16 18:43:00   
Weston          4.000000   2016-03-05 12:57:00 2016-06-05 15:57:00   
Westpark Place  2.182353   2016-02-26 11:05:00 2016-11-03 14:13:00   
Whitebridge     4.020588   2016-01-19 09:09:00 2016-11-03 13:42:00   
Winston Salem   133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00   

                                                                    \
                                                               max   
START_CITY      AVG_DIST   EARLIEST_TRAVEL                           
Agnew           2.775000   2016-11-04 21:04:00 2016-11-06 10:50:00   
Almond          15.200000  2016-10-30 12:58:00 2016-10-30 12:58:00   
Apex            5.341176   2016-01-29 21:21:00 2016-12-12 14:26:00   
Arabi           17.000000  2016-06-25 10:50:00 2016-06-25 10:50:00   
Arlington       4.900000   2016-08-02 11:51:00 2016-08-02 11:51:00   
...                                                            ...   
West University 2.200000   2016-03-10 14:39:00 2016-03-16 18:43:00   
Weston          4.000000   2016-03-05 12:57:00 2016-06-05 15:57:00   
Westpark Place  2.182353   2016-02-26 11:05:00 2016-11-03 14:13:00   
Whitebridge     4.020588   2016-01-19 09:09:00 2016-11-03 13:42:00   
Winston Salem   133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00   

                                                                    
                                                               min  
START_CITY      AVG_DIST   EARLIEST_TRAVEL                          
Agnew           2.775000   2016-11-04 21:04:00 2016-11-06 10:50:00  
Almond          15.200000  2016-10-30 12:58:00 2016-10-30 12:58:00  
Apex            5.341176   2016-01-29 21:21:00 2016-12-12 14:26:00  
Arabi           17.000000  2016-06-25 10:50:00 2016-06-25 10:50:00  
Arlington       4.900000   2016-08-02 11:51:00 2016-08-02 11:51:00  
...                                                            ...  
West University 2.200000   2016-03-10 14:39:00 2016-03-16 18:43:00  
Weston          4.000000   2016-03-05 12:57:00 2016-06-05 15:57:00  
Westpark Place  2.182353   2016-02-26 11:05:00 2016-11-03 14:13:00  
Whitebridge     4.020588   2016-01-19 09:09:00 2016-11-03 13:42:00  
Winston Salem   133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00  

[177 rows x 3 columns]

In [93]:
res


START_CITY    AVG_DIST     EARLIEST_TRAVEL       RECENT_TRAVEL
0              Agnew    2.775000 2016-11-04 21:04:00 2016-11-06 10:50:00
1             Almond   15.200000 2016-10-30 12:58:00 2016-10-30 12:58:00
2               Apex    5.341176 2016-01-29 21:21:00 2016-12-12 14:26:00
3              Arabi   17.000000 2016-06-25 10:50:00 2016-06-25 10:50:00
4          Arlington    4.900000 2016-08-02 11:51:00 2016-08-02 11:51:00
..               ...         ...                 ...                 ...
172  West University    2.200000 2016-03-10 14:39:00 2016-03-16 18:43:00
173           Weston    4.000000 2016-03-05 12:57:00 2016-06-05 15:57:00
174   Westpark Place    2.182353 2016-02-26 11:05:00 2016-11-03 14:13:00
175      Whitebridge    4.020588 2016-01-19 09:09:00 2016-11-03 13:42:00
176    Winston Salem  133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00

[177 rows x 4 columns]

In [94]:
res.to_csv("Demo.csv")

In [96]:
res.to_csv("D:\waste for pull and push the file\demo.csv")

# LOOPS AND FUNCTION

In [2]:
import pandas as pd
k=[1,2,3,4]
re=[i*i for i in k]

In [105]:
re

[1, 4, 9, 16]

In [3]:
sales=pd.read_csv("sales_data.csv")

In [107]:
sales

store_id        city  jan  feb  mar  apr  may  jun  jul  aug  sep  oct  nov  \
0      S_1       Erode    8   10   17    4   19    3   15   12   10   12   20   
1      S_2     Chennai   16   13   22   16    3   23   14   15   12    3   10   
2      S_3      Velure   12   12   19    9   13    6   10    9   17    6   17   
3      S_4  Thirupathi    8    6   21   15   11    9    8   14    5    9   14   
4      S_5  Coimbature   10   13   10   18    7   10   15   17   12    7    1   

   dec  
0   21  
1   24  
2   23  
3    1  
4   16

In [123]:
sales["jan"].mean()

10.8

In [122]:
sales.apply("mean")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9348\1347439220.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  sales.apply("mean")


jan    10.8
feb    10.8
mar    17.8
apr    12.4
may    10.6
jun    10.2
jul    12.4
aug    13.4
sep    11.2
oct     7.4
nov    12.4
dec    17.0
dtype: float64

In [125]:
sales.apply("mean",axis=0)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9348\1348365725.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  sales.apply("mean",axis=0)


jan    10.8
feb    10.8
mar    17.8
apr    12.4
may    10.6
jun    10.2
jul    12.4
aug    13.4
sep    11.2
oct     7.4
nov    12.4
dec    17.0
dtype: float64

In [126]:
sales.apply("mean",axis=1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9348\395565985.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sales.apply("mean",axis=1)


0    12.583333
1    14.250000
2    12.750000
3    10.083333
4    11.333333
dtype: float64

In [127]:
sales.select_dtypes(include=['int64','float64']).apply("mean")

jan    10.8
feb    10.8
mar    17.8
apr    12.4
may    10.6
jun    10.2
jul    12.4
aug    13.4
sep    11.2
oct     7.4
nov    12.4
dec    17.0
dtype: float64

In [1]:
sales["eligibility"]=np.where(sales.apply("mean",axis=1)>12,"Eligible","Not Eligible")

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [6]:
sales

store_id        city  jan  feb  mar  apr  may  jun  jul  aug  sep  oct  nov  \
0      S_1       Erode    8   10   17    4   19    3   15   12   10   12   20   
1      S_2     Chennai   16   13   22   16    3   23   14   15   12    3   10   
2      S_3      Velure   12   12   19    9   13    6   10    9   17    6   17   
3      S_4  Thirupathi    8    6   21   15   11    9    8   14    5    9   14   
4      S_5  Coimbature   10   13   10   18    7   10   15   17   12    7    1   

   dec  
0   21  
1   24  
2   23  
3    1  
4   16

In [8]:
def bonus_fun(list):
    elig_value=np.where(list>10,"Eligible","Not Eligible")
    return elig_value

In [9]:
sales["jan_bonus"]=bonus_fun(sales["jan"])

In [11]:
sales

store_id        city  jan  feb  mar  apr  may  jun  jul  aug  sep  oct  nov  \
0      S_1       Erode    8   10   17    4   19    3   15   12   10   12   20   
1      S_2     Chennai   16   13   22   16    3   23   14   15   12    3   10   
2      S_3      Velure   12   12   19    9   13    6   10    9   17    6   17   
3      S_4  Thirupathi    8    6   21   15   11    9    8   14    5    9   14   
4      S_5  Coimbature   10   13   10   18    7   10   15   17   12    7    1   

   dec     jan_bonus  
0   21  Not Eligible  
1   24      Eligible  
2   23      Eligible  
3    1  Not Eligible  
4   16  Not Eligible

In [5]:
import numpy as np
import pandas as pd
def bonus_fun2(list):
    value=np.where(list>10,"Eligible","Not Eligible")
    return value
newsales=sales.select_dtypes(include=['int64','float64']).apply(bonus_fun2)

In [6]:
newsales

jan           feb           mar           apr           may  \
0  Not Eligible  Not Eligible      Eligible  Not Eligible      Eligible   
1      Eligible      Eligible      Eligible      Eligible  Not Eligible   
2      Eligible      Eligible      Eligible  Not Eligible      Eligible   
3  Not Eligible  Not Eligible      Eligible      Eligible      Eligible   
4  Not Eligible      Eligible  Not Eligible      Eligible  Not Eligible   

            jun           jul           aug           sep           oct  \
0  Not Eligible      Eligible      Eligible  Not Eligible      Eligible   
1      Eligible      Eligible      Eligible      Eligible  Not Eligible   
2  Not Eligible  Not Eligible  Not Eligible      Eligible  Not Eligible   
3  Not Eligible  Not Eligible      Eligible  Not Eligible  Not Eligible   
4  Not Eligible      Eligible      Eligible      Eligible  Not Eligible   

            nov           dec  
0      Eligible      Eligible  
1  Not Eligible      Eligible  
2      Eligible      Eligible  
3      Eligible  Not Eligible  
4  Not Eligible      Eligible

In [7]:
sales

store_id        city  jan  feb  mar  apr  may  jun  jul  aug  sep  oct  nov  \
0      S_1       Erode    8   10   17    4   19    3   15   12   10   12   20   
1      S_2     Chennai   16   13   22   16    3   23   14   15   12    3   10   
2      S_3      Velure   12   12   19    9   13    6   10    9   17    6   17   
3      S_4  Thirupathi    8    6   21   15   11    9    8   14    5    9   14   
4      S_5  Coimbature   10   13   10   18    7   10   15   17   12    7    1   

   dec  
0   21  
1   24  
2   23  
3    1  
4   16

In [9]:
s=pd.concat([sales,newsales])

In [11]:
s

store_id        city           jan           feb           mar  \
0      S_1       Erode             8            10            17   
1      S_2     Chennai            16            13            22   
2      S_3      Velure            12            12            19   
3      S_4  Thirupathi             8             6            21   
4      S_5  Coimbature            10            13            10   
0      NaN         NaN  Not Eligible  Not Eligible      Eligible   
1      NaN         NaN      Eligible      Eligible      Eligible   
2      NaN         NaN      Eligible      Eligible      Eligible   
3      NaN         NaN  Not Eligible  Not Eligible      Eligible   
4      NaN         NaN  Not Eligible      Eligible  Not Eligible   

            apr           may           jun           jul           aug  \
0             4            19             3            15            12   
1            16             3            23            14            15   
2             9            13             6            10             9   
3            15            11             9             8            14   
4            18             7            10            15            17   
0  Not Eligible      Eligible  Not Eligible      Eligible      Eligible   
1      Eligible  Not Eligible      Eligible      Eligible      Eligible   
2  Not Eligible      Eligible  Not Eligible  Not Eligible  Not Eligible   
3      Eligible      Eligible  Not Eligible  Not Eligible      Eligible   
4      Eligible  Not Eligible  Not Eligible      Eligible      Eligible   

            sep           oct           nov           dec  
0            10            12            20            21  
1            12             3            10            24  
2            17             6            17            23  
3             5             9            14             1  
4            12             7             1            16  
0  Not Eligible      Eligible      Eligible      Eligible  
1      Eligible  Not Eligible  Not Eligible      Eligible  
2      Eligible  Not Eligible      Eligible      Eligible  
3  Not Eligible  Not Eligible      Eligible  Not Eligible  
4      Eligible  Not Eligible  Not Eligible      Eligible

In [12]:
salesconcat=pd.concat([sales,newsales],axis=1)

In [17]:
salesconcat


store_id        city  jan  feb  mar  apr  may  jun jul aug  ...  \
0      S_1       Erode    8   10   17    4   19    3  15  12  ...   
1      S_2     Chennai   16   13   22   16    3   23  14  15  ...   
2      S_3      Velure   12   12   19    9   13    6  10   9  ...   
3      S_4  Thirupathi    8    6   21   15   11    9   8  14  ...   
4      S_5  Coimbature   10   13   10   18    7   10  15  17  ...   

            mar           apr           may           jun           jul  \
0      Eligible  Not Eligible      Eligible  Not Eligible      Eligible   
1      Eligible      Eligible  Not Eligible      Eligible      Eligible   
2      Eligible  Not Eligible      Eligible  Not Eligible  Not Eligible   
3      Eligible      Eligible      Eligible  Not Eligible  Not Eligible   
4  Not Eligible      Eligible  Not Eligible  Not Eligible      Eligible   

            aug           sep           oct           nov           dec  
0      Eligible  Not Eligible      Eligible      Eligible      Eligible  
1      Eligible      Eligible  Not Eligible  Not Eligible      Eligible  
2  Not Eligible      Eligible  Not Eligible      Eligible      Eligible  
3      Eligible  Not Eligible  Not Eligible      Eligible  Not Eligible  
4      Eligible      Eligible  Not Eligible  Not Eligible      Eligible  

[5 rows x 26 columns]

In [14]:
salesconcat["jan"]

jan           jan
0   8  Not Eligible
1  16      Eligible
2  12      Eligible
3   8  Not Eligible
4  10  Not Eligible

In [22]:
salesconcat.select_dtype(include=["int64","float64"]).apply(["jan"])

AttributeError: 'DataFrame' object has no attribute 'select_dtype'

In [24]:
sales.isnull().sum()

store_id    0
city        0
jan         0
feb         0
mar         0
apr         0
may         0
jun         0
jul         0
aug         0
sep         0
oct         0
nov         0
dec         0
dtype: int64

In [25]:
sales

store_id        city  jan  feb  mar  apr  may  jun  jul  aug  sep  oct  nov  \
0      S_1       Erode    8   10   17    4   19    3   15   12   10   12   20   
1      S_2     Chennai   16   13   22   16    3   23   14   15   12    3   10   
2      S_3      Velure   12   12   19    9   13    6   10    9   17    6   17   
3      S_4  Thirupathi    8    6   21   15   11    9    8   14    5    9   14   
4      S_5  Coimbature   10   13   10   18    7   10   15   17   12    7    1   

   dec  
0   21  
1   24  
2   23  
3    1  
4   16

In [27]:
sales["city"].value_counts()

Erode         1
Chennai       1
Velure        1
Thirupathi    1
Coimbature    1
Name: city, dtype: int64

In [43]:
df=salesconcat.fillna({"jan":"16"})
df

store_id        city jan  feb  mar  apr  may  jun jul aug  ...  \
0      S_1       Erode   8   10   17    4   19    3  15  12  ...   
1      S_2     Chennai  16   13   22   16    3   23  14  15  ...   
2      S_3      Velure  12   12   19    9   13    6  10   9  ...   
3      S_4  Thirupathi   8    6   21   15   11    9   8  14  ...   
4      S_5  Coimbature  10   13   10   18    7   10  15  17  ...   

            mar           apr           may           jun           jul  \
0      Eligible  Not Eligible      Eligible  Not Eligible      Eligible   
1      Eligible      Eligible  Not Eligible      Eligible      Eligible   
2      Eligible  Not Eligible      Eligible  Not Eligible  Not Eligible   
3      Eligible      Eligible      Eligible  Not Eligible  Not Eligible   
4  Not Eligible      Eligible  Not Eligible  Not Eligible      Eligible   

            aug           sep           oct           nov           dec  
0      Eligible  Not Eligible      Eligible      Eligible      Eligible  
1      Eligible      Eligible  Not Eligible  Not Eligible      Eligible  
2  Not Eligible      Eligible  Not Eligible      Eligible      Eligible  
3      Eligible  Not Eligible  Not Eligible      Eligible  Not Eligible  
4      Eligible      Eligible  Not Eligible  Not Eligible      Eligible  

[5 rows x 26 columns]

In [44]:
df["city"].value_counts()

Erode         1
Chennai       1
Velure        1
Thirupathi    1
Coimbature    1
Name: city, dtype: int64

# ADVANCE PYTHON DATA SCIENCE

In [47]:
# must giv the "/" at the last
your_local_path="D:/data_Science/"

In [48]:
def func_python(N):
    d=0
    for i in range(N):
        d+=(i%3-i)*i
    return d

In [51]:
%timeit func_python(10)

3.99 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [52]:
distance=[45,50,35]
speed=[5,10,7]

In [54]:
time=distance/speed
print(time)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

# intro to numpy
  #### Numpy( short form for Numerical Python) is a most fundamental package designed for scientific computing and data analysis. Most of the other Packages such as pandas, statsmodels are build on top of it. at the heart of NumPY is a data Structure called ndarray. ndarray  is a basically a multi dimentional array that is built specifically for the purpose of numerical data analysis. python also have array capability but the are more generic. 
 ### the advantage of using ndarray is that processing is extremely efficient and fast.
   ####  You the range function covered is linear algebra, statistical operation and other specialized function relavent to other research purpose
   #### undresting of numpy hepl to use pandas efficienly
## POSSIBLE APPLICATION OF NumPy in research work are:
   ### 1-->Algorithm operation such as sorting, grouping, and set operations
   ### 2--> Performing repetitive function on whole array of data without using loop
   ### 3--> Data Merging and alignment Operation
   ### 4--> Data indexing, filtering, and Transforming on individual element or whole arrays
   ### 5--> data summarization and description statistics

In [55]:
import numpy as np

In [56]:
from numpy import array

In [57]:
from numpy import arange

In [58]:
distance=[45,50,35]
speed=[5,10,7]
dist =array(distance)
spd=np.array(speed)

In [60]:
print(dist)
print(spd)

[45 50 35]
[ 5 10  7]


In [62]:
time=dist/spd
print(time)

[9. 5. 5.]


In [63]:
len(time)

3

# ndarrsy
  ### the most important data structure in numpy is n-dimentional array object. using ndarray, you can store large multidimentional dataset in python. being an array, you can perform mathimatical operation on these array either one element at a time or on complete arrays without using loop. 

In [66]:
a=[1,2,3,4,5]
b=[10,20,30,40]
print(a+b)
#print(a+5) -->Error:can only concatenate list (not "int") to list
c=[val+5 for val in a]
print(c)

[1, 2, 3, 4, 5, 10, 20, 30, 40]
[6, 7, 8, 9, 10]


In [68]:
f=array((1,2,3,4,5))
g=array((10,20,30,40))
print(f,g,a,b)

[1 2 3 4 5] [10 20 30 40] [1, 2, 3, 4, 5] [10, 20, 30, 40]


In [73]:
#print(f+g) #-->error 
print(f+5)
#print(a+5)#--> error

[ 6  7  8  9 10]


In [74]:
c=array(arange(10))

In [75]:
print('array:   ',c)

array:    [0 1 2 3 4 5 6 7 8 9]


In [76]:
anarray=array(np.arange(5,56,5))
print(anarray)
print()

[ 5 10 15 20 25 30 35 40 45 50 55]



In [80]:

onemorearray=array(np.arange(3,4,13))
onemorearray=array(np.arange(3,4,0.5))
print(onemorearray)
print('round onemorearray : ',np.round(onemorearray,0))
print(onemorearray.sum())

[3.  3.5]
round onemorearray :  [3. 4.]
6.5


  ### ndarray are associated with 2 attributes 1--> shape of the array and type of the array.
   ### shape of the array tell about dimentinality of the array(rows and column
   ### types of the array tell about data type contained in the array

In [83]:
data=np.array((32,45,123,756,23,2123,1,2,3,4,5,6,7,8,6,5,4,3,2,1,78,89,87,76,54,31))
print(data)

[  32   45  123  756   23 2123    1    2    3    4    5    6    7    8
    6    5    4    3    2    1   78   89   87   76   54   31]


In [85]:
data2=data.reshape(2,2,2,3) # ->error : cannot reshape array of size 26 into shape (2,2,2,3)

ValueError: cannot reshape array of size 26 into shape (2,2,2,3)

In [86]:
print("*****")

*****


In [87]:
data2=data.reshape(2,2,2,3) # ->error :

ValueError: cannot reshape array of size 26 into shape (2,2,2,3)

In [88]:
print(data.dtype)

int32


In [89]:
print(data.size)

26


In [92]:
event_data=(data%2==0)

In [93]:
print(event_data)

[ True False False  True False False False  True False  True False  True
 False  True  True False  True False  True False  True False False  True
  True False]


In [95]:
data[event_data] # print all the true values

array([ 32, 756,   2,   4,   6,   8,   6,   4,   2,  78,  76,  54])

In [96]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
np.zeros((3,5))+6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [98]:
np.ones(30)+7

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [99]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [100]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [101]:
  np.eye(5)    # create a identity 5*5 matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
np.diag(array([1,3,5,3,4,5])) # populate the disgonal elements only

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

# Pandas
###        pandas is a primary packages for performing data analysis .it derives its name from PANeI Data AnalysiS and is the fundamental package that provide relatinal dat structure(Excel ,SQL)  and host of play with those data structure. it is very good to work with cross sectional, time series , and panel data analysis 

## 2 basic data structure series and DataFrame

In [120]:
series1=pd.Series([10,20,30,40,50])

In [105]:
print(series1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [107]:
series1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [109]:
series1.index

RangeIndex(start=0, stop=5, step=1)

In [111]:
# if you want specify custom index value rather than the default one provider 
#you can use
series2=pd.Series([10,20,30,40,50],index=[1,2,3,4,5])
series2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [119]:
series[5]

NameError: name 'series' is not defined

In [122]:
series2+4

1    14
2    24
3    34
4    44
5    54
dtype: int64

In [124]:
series2**2

1     100
2     400
3     900
4    1600
5    2500
dtype: int64

In [125]:
np.sqrt(series2)

1    3.162278
2    4.472136
3    5.477226
4    6.324555
5    7.071068
dtype: float64

In [127]:
years=[91,90,92,93,94,95,96,97]
f1={90:8,91:9,92:7,93:8,94:9,95:11,96:13}
firm1=pd.Series(f1,index=years)
firm1

91     9.0
90     8.0
92     7.0
93     8.0
94     9.0
95    11.0
96    13.0
97     NaN
dtype: float64

In [ ]:
import pan